#                                                                        #
# Routes configuration for the Newsletter package                        #
#                                                                        #
#
# In order to activate those routes, add the following snippet to the main
# Routes.yaml file of your distribution:
#
#-
#  name: 'Subscription'
#  uriPattern: '<NewsletterSubroutes>'
#  subRoutes:
#    'NewsletterSubroutes':
#      package: 'Psmb.Newsletter'

-
  name: 'Psmb.Newsletter edit route'
  uriPattern: '{node}~newsletter/edit/{--newsletter.subscriber}'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--newsletter':
      '@package': 'Psmb.Newsletter'
      '@controller': 'Subscription'
      '@action': 'edit'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

-
  name: 'Psmb.Newsletter unsubscribe route'
  uriPattern: '{node}~newsletter/unsubscribe/{--newsletter.subscriber}'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--newsletter':
      '@package': 'Psmb.Newsletter'
      '@controller': 'Subscription'
      '@action': 'unsubscribe'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

-
  name: 'Psmb.Newsletter other routes'
  uriPattern: '{node}~newsletter/{--newsletter.@action}'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--newsletter':
      '@package': 'Psmb.Newsletter'
      '@controller': 'Subscription'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

-
  name: 'Psmb.Newsletter send action'
  uriPattern: 'newsletter/{@action}'
  defaults:
    '@package':    'Psmb.Newsletter'
    '@controller': 'Newsletter'
    '@format':     'json'
    '@action':     'send'
  appendExceedingArguments: TRUE