
Flowpack:
  JobQueue:
    Common:
      queues:
        psmb-newsletter:
          className: Flowpack\JobQueue\Common\Queue\FakeQueue
        psmb-newsletter-web:
          className: Flowpack\JobQueue\Common\Queue\FakeQueue
          options:
            async: true
Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Psmb.Newsletter:Backend':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Psmb\Newsletter\Controller\.*'
    mvc:
      routes:
        'Psmb.Newsletter':
          position: 'before Neos.Neos'
  Neos:
    userInterface:
      translation:
        autoInclude:
          Psmb.Newsletter:
            - Main
            - 'NodeTypes/*'
      requireJsPathMapping:
        Psmb.Newsletter/Views: 'resource://Psmb.Newsletter/Public/JavaScript/Inspector/Views'
    fusion:
      autoInclude:
        Psmb.Newsletter: true

#Psmb:
#  Newsletter:
#    globalSettings:
#      senderAddress: 'robot@server.com'
#      senderName: 'Your robot'
#    subscriptions:
#      -
#        identifier: 'daily'
#        renderer: 'Your:LetterRenderer'
#        sendFromUiNodeType: 'Your:NodeType'
#        label: 'Our daily newsletter'
#        interval: P1D
#        dimensions:
#          language: ['dimensionValues']
