TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Psmb.Newsletter': TRUE
#Psmb:
#  Newsletter:
#    globalSettings:
#      senderAddress: 'robot@server.com'
#      senderName: 'Your robot'
#    subscriptions:
#      -
#        identifier: 'daily'
#        renderer: 'Your:LetterRenderer'
#        label: 'Our daily newsletter'
#        interval: P1D
#        dimensions:
#          language: ['dimensionValues']
