TYPO3:
  Flow:
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            requestPatterns:
              'Psmb.Newsletter:Backend':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Psmb\Newsletter\Controller\.*'
  Neos:
    typoScript:
      autoInclude:
        'Psmb.Newsletter': TRUE
    userInterface:
      translation:
        autoInclude:
          'Psmb.Newsletter': ['Main', 'NodeTypes/*']
      requireJsPathMapping:
        'Psmb.Newsletter/Views': 'resource://Psmb.Newsletter/Public/JavaScript/Inspector/Views'
    modules:
      management:
        submodules:
          newsletter:
            label: 'Newsletter'
            controller: 'Psmb\Newsletter\Controller\BackendController'
            description: 'Manage all subscriber lists for your Newsletter. You can edit/delete/update each subscription individually. Keep in mind that all subscribers are detached from Neos users.'
            icon: 'icon-envelope'
            privilegeTarget: 'Psmb.Newsletter:BackendModule'
Psmb:
  Newsletter:
    module:
      itemsPerPage: 10
#    globalSettings:
#      senderAddress: 'robot@server.com'
#      senderName: 'Your robot'
#    subscriptions:
#      -
#        identifier: 'daily'
#        renderer: 'Your:LetterRenderer'
#        label: 'Our daily newsletter'
#        interval: P1D
#        dimensions:
#          language: ['dimensionValues']
